import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDate, formatMoney } from "@/lib/utils";
import { drawLetterhead } from "./letterhead";
import type { InvoiceItem, PartyType } from "@/lib/types/database";

export type InvoicePdfData = {
  invoice_no: string;
  party_type: PartyType;
  party_name: string;
  party_detail: string | null;
  items: InvoiceItem[];
  total: number;
  paid: number;
  balance: number;
  status: string;
  issued_date: string;
  due_date: string | null;
  note: string | null;
};

export function downloadInvoicePdf(inv: InvoicePdfData) {
  const doc = new jsPDF();
  drawLetterhead(doc, "Invoice");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  // A student invoice bills the student; a teacher/staff invoice is a
  // payment voucher in the person's favour.
  doc.text(inv.party_type === "student" ? "Billed to" : "Payable to", 14, 40);
  doc.setFont("helvetica", "normal");
  doc.text(inv.party_name, 14, 46);
  doc.setTextColor(100);
  doc.text(inv.party_detail ?? partyTypeLabel(inv.party_type), 14, 52);
  doc.setTextColor(0);

  doc.setFont("helvetica", "bold");
  doc.text(inv.invoice_no, 196, 40, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Issued: ${formatDate(inv.issued_date)}`, 196, 46, { align: "right" });
  if (inv.due_date) doc.text(`Due: ${formatDate(inv.due_date)}`, 196, 52, { align: "right" });
  doc.setTextColor(0);

  autoTable(doc, {
    startY: 60,
    head: [["#", "Description", "Qty", "Unit price", "Amount"]],
    body: inv.items.map((it, i) => [
      String(i + 1),
      it.description,
      String(it.qty),
      formatMoney(it.unit_price),
      formatMoney(it.qty * it.unit_price),
    ]),
    theme: "grid",
    headStyles: { fillColor: [0, 122, 255] },
    columnStyles: {
      0: { cellWidth: 10 },
      2: { cellWidth: 16, halign: "right" },
      3: { cellWidth: 28, halign: "right" },
      4: { cellWidth: 28, halign: "right" },
    },
  });

  let y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  const totals: Array<[string, string, boolean]> = [
    ["Total", formatMoney(inv.total), false],
    ["Paid to date", formatMoney(inv.paid), false],
    ["Balance due", formatMoney(inv.balance), true],
  ];
  totals.forEach(([label, value, strong]) => {
    doc.setFont("helvetica", strong ? "bold" : "normal");
    doc.setFontSize(strong ? 11 : 10);
    doc.text(label, 140, y);
    doc.text(value, 196, y, { align: "right" });
    y += 6.5;
  });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(`Status: ${inv.status.toUpperCase()}`, 14, y - 6.5);
  doc.setFont("helvetica", "normal");

  if (inv.note) {
    y += 4;
    doc.setFontSize(9.5);
    doc.setTextColor(100);
    doc.text(`Note: ${inv.note}`, 14, y, { maxWidth: 182 });
    doc.setTextColor(0);
  }

  doc.setDrawColor(180);
  doc.line(14, 268, 74, 268);
  doc.line(136, 268, 196, 268);
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text("Prepared by", 14, 273);
  doc.text("Authorized signature", 136, 273);
  doc.text("Generated by the Sh.Asharow LMS.", 14, 285);

  doc.save(`${inv.invoice_no.toLowerCase()}-${slug(inv.party_name)}.pdf`);
}

function partyTypeLabel(type: PartyType) {
  return type === "student" ? "Student" : type === "teacher" ? "Teacher" : "Staff";
}

function slug(name: string) {
  return name.trim().toLowerCase().replace(/\s+/g, "-");
}
