import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDate, formatMoney } from "@/lib/utils";
import { drawLetterhead } from "./letterhead";
import type { PartyType, PaymentMethod } from "@/lib/types/database";

export type ReceiptPdfData = {
  receipt_no: string;
  invoice_no: string | null;
  party_type: PartyType;
  party_name: string;
  party_detail: string | null;
  amount: number;
  method: PaymentMethod;
  note: string | null;
  received_at: string;
};

const METHOD_LABELS: Record<PaymentMethod, string> = {
  cash: "Cash",
  mobile_money: "Mobile Money",
  bank_transfer: "Bank Transfer",
  other: "Other",
};

export function downloadReceiptPdf(rct: ReceiptPdfData) {
  const doc = new jsPDF();
  drawLetterhead(doc, "Payment Receipt");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  // Money comes in from students; salaries and wages go out to
  // teachers and other staff.
  doc.text(rct.party_type === "student" ? "Received from" : "Paid to", 14, 40);
  doc.setFont("helvetica", "normal");
  doc.text(rct.party_name, 14, 46);
  doc.setTextColor(100);
  doc.text(rct.party_detail ?? partyTypeLabel(rct.party_type), 14, 52);
  doc.setTextColor(0);

  doc.setFont("helvetica", "bold");
  doc.text(rct.receipt_no, 196, 40, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Date: ${formatDate(rct.received_at)}`, 196, 46, { align: "right" });
  if (rct.invoice_no) doc.text(`Invoice: ${rct.invoice_no}`, 196, 52, { align: "right" });
  doc.setTextColor(0);

  autoTable(doc, {
    startY: 60,
    head: [["Description", "Method", "Amount"]],
    body: [
      [
        rct.note ?? (rct.invoice_no ? `Payment against invoice ${rct.invoice_no}` : "Payment"),
        METHOD_LABELS[rct.method],
        formatMoney(rct.amount),
      ],
    ],
    theme: "grid",
    headStyles: { fillColor: [0, 122, 255] },
    columnStyles: { 1: { cellWidth: 36 }, 2: { cellWidth: 30, halign: "right" } },
  });

  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Amount ${rct.party_type === "student" ? "received" : "paid"}: ${formatMoney(rct.amount)}`, 14, y);
  doc.setFont("helvetica", "normal");

  doc.setDrawColor(180);
  doc.line(14, 268, 74, 268);
  doc.line(136, 268, 196, 268);
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text("Received by", 14, 273);
  doc.text(rct.party_type === "student" ? "Payer signature" : "Payee signature", 136, 273);
  doc.text("Generated by the Sh.Asharow LMS.", 14, 285);

  doc.save(`${rct.receipt_no.toLowerCase()}-${slug(rct.party_name)}.pdf`);
}

function partyTypeLabel(type: PartyType) {
  return type === "student" ? "Student" : type === "teacher" ? "Teacher" : "Staff";
}

function slug(name: string) {
  return name.trim().toLowerCase().replace(/\s+/g, "-");
}
