import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { drawLetterhead } from "./letterhead";

export type ReportCardData = {
  student_name: string;
  class_name: string | null;
  term1: number | null;
  term2: number | null;
  term3: number | null;
  average: number;
  grade: string;
};

export function downloadReportCard(record: ReportCardData) {
  const doc = new jsPDF();
  drawLetterhead(doc, "Academic Report Card");

  doc.setFontSize(10);
  doc.text(`Student: ${record.student_name}`, 14, 40);
  doc.text(`Class: ${record.class_name ?? "—"}`, 14, 46);
  doc.text(`Issued: ${new Date().toLocaleDateString()}`, 14, 52);

  autoTable(doc, {
    startY: 60,
    head: [["Term 1", "Term 2", "Term 3", "Average", "Grade"]],
    body: [
      [record.term1 ?? "—", record.term2 ?? "—", record.term3 ?? "—", record.average, record.grade],
    ],
    theme: "grid",
    headStyles: { fillColor: [0, 122, 255] },
  });

  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text("Generated by the Sh.Asharow LMS.", 14, 285);

  doc.save(`report-card-${slug(record.student_name)}.pdf`);
}

function slug(name: string) {
  return name.trim().toLowerCase().replace(/\s+/g, "-");
}
